services:

  backend:
    build:
      context: services/backend
    stop_signal: SIGKILL
    container_name: flask_app
    ports:
      - 8000:8000
    volumes:
      - './services/backend/src:/app'
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


  postgres:
    container_name: database_postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=networks_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./db2/:/var/lib/postgresql/data
      - ./db2/:/var/lib/postgresql/log_db
    command:
      postgres -c log_destination=stderr
               -c logging_collector=on
               -c log_directory=log_db
