name: CI Pipeline  # Название Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # ОС для запуска
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Шаг 1: Клонирование репозитория

      - name: Build Docker
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
      - name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

