name: CI Pipeline  # Название Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # ОС для запуска
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Шаг 1: Клонирование репозитория
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker
        run: |
          docker-compose -f network_wiki/network_wiki/docker-compose.yml build
          docker-compose -f network_wiki/network_wiki/docker-compose.yml push
      - name: Start Docker Compose services
        run: |
          docker-compose -f network_wiki/network_wiki/docker-compose.yml up -d
      - name: Stop Docker containers
        if: always()  # Останавливает контейнеры даже если тесты упали
        run: |
          docker-compose -f network_wiki/network_wiki/docker-compose.yml down

