name: FastAPI CI

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      # Шаг 3: Сборка и запуск контейнеров
      - name: Start containers
        run: docker-compose up -d
          
      # # Шаг 2: Установка Python
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.12"  # Укажите версию Python, которую используете

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx  # Установка тестовых зависимостей

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: |
          pytest

      # (Опционально) Шаг 5: Проверка стиля кода с помощью black
      - name: Check code formatting with black
        run: |
          pip install black
          black --check .

      # (Опционально) Шаг 6: Проверка стиля кода с помощью flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      # (Опционально) Шаг 7: Проверка типов с помощью mypy
      - name: Run mypy
        run: |
          pip install mypy
          mypy .
