
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v3

      - name: Установка библиотек из requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r network_wiki/services/backend/requirements.txt
          
      - name: Скачивание Docker-Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Сборка контейнеров Docker-Compose
        run: |
          docker-compose -f network_wiki/docker-compose.yaml build
          
      - name: Старт контейнера Posetgres
        run: |
          docker-compose -f network_wiki/docker-compose.yaml up -d postgres
          
      - name: Проверка запуска Postgres
        run: |
          echo "Waiting for PostgreSQL to start..."
          until docker-compose -f network_wiki/docker-compose.yaml exec postgres pg_isready -U admin -d networks_db; do
            echo "PostgreSQL is not ready yet. Retrying in 5 seconds..."
            sleep 5
          done
          echo "PostgreSQL is ready!"
          
      - name: Старт контейнера FastApi
        run: |
          docker-compose -f network_wiki/docker-compose.yaml up -d backend
          sleep 15
             
      - name: Запуск тестов
        run: |
          pytest network_wiki/services/backend/src/tests/test_app.py

      - name: Запуск и исправление кода с помощью black
        run: |
          black network_wiki/services/backend
          
      - name: Запуск теста с Pylint
        run: |
          pylint --init-hook="import sys; sys.path.append('network_wiki/services/backend/src/')" network_wiki/services/backend/src/

      - name: Запуск теста с Flake8
        run: |
          flake8 network_wiki/services/backend

      - name: Запуск теста с Isort
        run: |
          isort network_wiki/services/backend
          
      - name: Остановка контейнеров Docker-Compose
        if: always()
        run: |
          docker-compose -f network_wiki/docker-compose.yaml down
