name: CI Pipeline  # Название Workflow

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # ОС для запуска
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Шаг 1: Клонирование репозитория
      - name: Build Docker image
        run: |
          docker compose up
